# Generated by Django 5.1.4 on 2024-12-11 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solution_amount_to_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solution',
            name='amount_to_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Required for 'sell' solutions", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='amount_willing_to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Required for 'request' solutions", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Enter a valid mobile number in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
        ),
    ]
